### ISSUE TITLE
find: illegal option on MacOS

### ISSUE THREAD

**Issue by ycmjason** [voronkovich/ctrlp-nerdtree.vim#2]
Thanks for the nice plugin! I have been using it on a linux machine and it works great.

But I recently install this on my macbook, but it keeps on showing the following message:

```
> find: illegal option -- t
> usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
>        find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

**Comment by ycmjason** [comment]
I have solved this by updating `find`.

```
brew install findutils
```

**Comment by voronkovich** [comment]
@ycmjason, thanks for the found solution! I've updated the installation instructions.
